// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("xmodel/oma_mc_hunter");
	//self attach("xmodel/head_us_ranger_preston", "", true);
	self setViewmodel("xmodel/oma_mc_hand");
}

precache()
{
	precacheModel("xmodel/oma_mc_hunter");
	precacheModel("xmodel/head_us_ranger_preston");
	precacheModel("xmodel/oma_mc_hand");
}